# Generated by Django 5.2.9 on 2026-08-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accuracy",
            field=models.FloatField(default=0.0, verbose_name="准确率"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "管理员"), ("user", "普通用户")],
                default="user",
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
