# Generated by Django 5.2.12 on 2026-08-14 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("detection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "report_name",
                    models.CharField(default="", max_length=128, verbose_name="报告名称"),
                ),
                (
                    "total_images",
                    models.PositiveIntegerField(default=0, verbose_name="图片总数"),
                ),
                (
                    "total_defects",
                    models.PositiveIntegerField(default=0, verbose_name="缺陷总数"),
                ),
                ("accuracy", models.FloatField(default=0.0, verbose_name="平均置信度")),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/", verbose_name="报告文件"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="detection.detectionproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测报告",
                "verbose_name_plural": "检测报告",
                "db_table": "inspection_report",
                "ordering": ["-created_at"],
            },
        ),
    ]
