# Generated by Django 5.2.12 on 2026-08-14 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionreport",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="detection.detectionimage",
                verbose_name="关联图片",
            ),
        ),
        migrations.AddField(
            model_name="inspectionreport",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="detection.detectiontask",
                verbose_name="关联任务",
            ),
        ),
        migrations.CreateModel(
            name="ReportRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=5, verbose_name="评分"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="评价内容"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="reports.inspectionreport",
                        verbose_name="所属报告",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评价人",
                    ),
                ),
            ],
            options={
                "verbose_name": "报告评价",
                "verbose_name_plural": "报告评价",
                "db_table": "report_rating",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "user"), name="uniq_report_user_rating"
                    )
                ],
            },
        ),
    ]
