# Generated by Django 5.2.9 on 2026-08-15 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_inspectionreport_image_inspectionreport_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectionreport",
            name="project",
        ),
    ]
