# Generated by Django 5.2.12 on 2026-08-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "defect_type",
                    models.CharField(
                        choices=[
                            ("crack", "裂缝"),
                            ("spalling", "剥落"),
                            ("pothole", "坑洞"),
                            ("corrosion", "钢筋锈蚀"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="缺陷类型",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0, verbose_name="置信度")),
                ("x1", models.FloatField(default=0, verbose_name="左上角 x")),
                ("y1", models.FloatField(default=0, verbose_name="左上角 y")),
                ("x2", models.FloatField(default=0, verbose_name="右下角 x")),
                ("y2", models.FloatField(default=0, verbose_name="右下角 y")),
                ("area", models.FloatField(default=0, verbose_name="面积")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="detection.detectionimage",
                        verbose_name="所属图片",
                    ),
                ),
            ],
            options={
                "verbose_name": "缺陷",
                "verbose_name_plural": "缺陷",
                "db_table": "defect",
                "ordering": ["-confidence"],
                "indexes": [
                    models.Index(
                        fields=["defect_type", "confidence"],
                        name="defect_defect__c84746_idx",
                    )
                ],
            },
        ),
    ]
