# Generated by Django 5.2.12 on 2026-08-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defect",
            name="source",
            field=models.CharField(
                db_index=True, default="bridge", max_length=16, verbose_name="检测模型来源"
            ),
        ),
    ]
