# Generated by Django 5.2.12 on 2026-08-14 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("project_name", models.CharField(max_length=128, verbose_name="项目名称")),
                (
                    "project_code",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="项目编号"
                    ),
                ),
                (
                    "bridge_name",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="桥梁名称"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="位置"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测项目",
                "verbose_name_plural": "检测项目",
                "db_table": "detection_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "task_name",
                    models.CharField(default="", max_length=128, verbose_name="任务名称"),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, default="yolov8", max_length=64, verbose_name="模型名称"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, default="v1", max_length=32, verbose_name="模型版本"
                    ),
                ),
                (
                    "image_count",
                    models.PositiveIntegerField(default=0, verbose_name="图片数量"),
                ),
                (
                    "defect_count",
                    models.PositiveIntegerField(default=0, verbose_name="缺陷数量"),
                ),
                ("accuracy", models.FloatField(default=0.0, verbose_name="平均置信度")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("running", "检测中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="detection.detectionproject",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测任务",
                "verbose_name_plural": "检测任务",
                "db_table": "detection_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "original_image",
                    models.ImageField(
                        upload_to="detection/original/", verbose_name="原图"
                    ),
                ),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="detection/result/",
                        verbose_name="结果图",
                    ),
                ),
                (
                    "image_width",
                    models.PositiveIntegerField(default=0, verbose_name="图片宽度"),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(default=0, verbose_name="图片高度"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="detection.detectiontask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测图片",
                "verbose_name_plural": "检测图片",
                "db_table": "detection_image",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="detectiontask",
            index=models.Index(
                fields=["status", "created_at"], name="detection_t_status_24bc4f_idx"
            ),
        ),
    ]
