# Generated by Django 5.2.9 on 2026-08-15 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0001_initial"),
        ("reports", "0003_remove_inspectionreport_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectiontask",
            name="project",
        ),
        migrations.DeleteModel(
            name="DetectionProject",
        ),
    ]
